"""empty message

Revision ID: 0a4c46cbc064
Revises: ac6dc3c1ca1c
Create Date: 2022-12-06 23:19:22.149854

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a4c46cbc064'
down_revision = 'ac6dc3c1ca1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vaccine_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hospital_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('vaccine_name', sa.String(length=100), nullable=True))
        batch_op.drop_constraint('vaccine_request_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'hospital', ['hospital_id'], ['hospital_id'])
        batch_op.drop_column('Hospital_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vaccine_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Hospital_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('vaccine_request_ibfk_1', 'hospital', ['Hospital_id'], ['hospital_id'])
        batch_op.drop_column('vaccine_name')
        batch_op.drop_column('hospital_id')

    # ### end Alembic commands ###
