"""empty message

Revision ID: 9a4ce9f4e370
Revises: a5229c0fcf73
Create Date: 2022-11-21 14:52:53.201535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a4ce9f4e370'
down_revision = 'a5229c0fcf73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vaccine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vaccine_serial', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vaccine', schema=None) as batch_op:
        batch_op.drop_column('vaccine_serial')

    # ### end Alembic commands ###
