"""empty message

Revision ID: 9ff85cfd7337
Revises: c0e0651b9508
Create Date: 2022-11-21 22:52:12.697026

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9ff85cfd7337'
down_revision = 'c0e0651b9508'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospital', schema=None) as batch_op:
        batch_op.drop_column('v_stock_count')
        batch_op.drop_column('vaccine_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospital', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vaccine_name', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('v_stock_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
