"""empty message

Revision ID: ac6dc3c1ca1c
Revises: 
Create Date: 2022-12-06 22:25:44.389704

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ac6dc3c1ca1c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vaccine_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vaccine_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('Hospital_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('request_amount', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('request_status', sa.String(length=100), nullable=True))
        batch_op.create_foreign_key(None, 'hospital', ['Hospital_id'], ['hospital_id'])
        batch_op.create_foreign_key(None, 'vaccine', ['vaccine_id'], ['vaccine_serial'])
        batch_op.drop_column('vaccine_name')
        batch_op.drop_column('date')
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vaccine_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('date', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('vaccine_name', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('request_status')
        batch_op.drop_column('request_amount')
        batch_op.drop_column('Hospital_id')
        batch_op.drop_column('vaccine_id')

    # ### end Alembic commands ###
