"""empty message

Revision ID: cc16bf662b7a
Revises: 
Create Date: 2022-11-29 06:13:31.345520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc16bf662b7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user__vaccine__info', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'regular_user', ['v_user_id'], ['nid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user__vaccine__info', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
